# netlify.toml
# Configuration for Netlify deployment

[build]
  publish = "dist"
  command = "npm run build && cp ./public/mockServiceWorker.js ./dist/"

# Handle SPA routing - redirect all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Explicitly allow the service worker file
[[headers]]
  for = "/mockServiceWorker.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-store"